require: rubocop-rails
AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/development.rb'
    - 'config/initializers/redis.rb'
    - 'lib/tasks/auto_annotate_models.rake'

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/TrailingEmptyLines:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  CountRepeatedAttributes: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 100

Naming/AccessorMethodName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Rails/EagerEvaluationLogMessage:
  Enabled: false

Rails/Delegate:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/OpenStructUse:
  Enabled: false